{{- range $serviceName, $service := .Values.services }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $serviceName }}
  namespace: argocd
spec:
  project: services
  source:
    repoURL: https://github.com/b-dorsal/infra-reference.git
    targetRevision: main
    path: infra-reference/helm/microservice
    helm:
      releaseName: {{ $serviceName }}
      # valueFiles:
      #   -
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap
  namespace: default
data:
  key1: {{ .Values.foo }}
  key2: value2