{{- range $serviceName, $service := .Values.services }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $serviceName }}
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: {{ $serviceName | replace "/" "--" }}={{ $service.repos.image }}
    argocd-image-updater.argoproj.io/{{ $serviceName | replace "/" "--" }}.update-strategy: latest
spec:
  project: {{ include "env-config.name" . }}
  source:
    repoURL: https://github.com/b-dorsal/infra-reference.git
    targetRevision: main
    path: helm/microservice
    helm:
      releaseName: {{ $serviceName }}
      valueFiles:
        - ../../config/services/{{ $serviceName }}.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
{{- end }}