{{- range $serviceName, $service := .Values.services }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $serviceName }}
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: {{ $service.repos.image }}
    argocd-image-updater.argoproj.io/bdor528-sample-service.update-strategy: latest
spec:
  project: {{ "env-config.name" }}
  source:
    repoURL: https://github.com/b-dorsal/infra-reference.git
    targetRevision: argo-setup
    path: helm/microservice
    helm:
      releaseName: {{ $serviceName }}
      valueFiles:
        - ../../config/services/{{ $serviceName }}.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
{{- end }}