{{- range $serviceName, $service := .Values.services }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $serviceName }}
  namespace: argocd
spec:
  project: {{ "env-config.name" }}
  source:
    repoURL: https://github.com/b-dorsal/infra-reference.git
    targetRevision: argo-setup
    path: helm/microservice
    helm:
      releaseName: {{ $serviceName }}
      # valueFiles:
      #   -
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}