apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ include "env-config.name" . }}.{{ .Values.name }}
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
