apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  targetNamespace: tekton-pipelines
  targetNamespaceMetadata:
    labels: {}
    annotations: {}
  chain:
    disabled: true
  pipeline:
    options:
      deployments:
        tekton-pipelines-controller:
          spec:
            template:
              spec:
                containers:
                  - name: tekton-pipelines-controller
                    resources:
                      limits:
                        cpu: 250m
                        memory: 500Mi
                      requests:
                        cpu: 250m
                        memory: 500Mi
  dashboard:
    readonly: false
    options:
      disabled: false
      deployments:
        tekton-dashboard:
          spec:
            template:
              spec:
                containers:
                  - name: tekton-dashboard
                    resources:
                      limits:
                        cpu: 250m
                        memory: 500Mi
                      requests:
                        cpu: 250m
                        memory: 500Mi
  pruner:
    disabled: false
    schedule: "0 8 * * *"
    resources:
      - taskrun
      - pipelinerun
    keep: 3
    prune-per-resource: true