apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: tekton.local
    http:
      paths:
      - path: /
        backend:
          serviceName: tekton-dashboard
          servicePort: 9097